root: true

parserOptions:
  ecmaVersion: latest

env:
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

plugins:
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

ignorePatterns:
  - build/
